### ISSUE TITLE
Error: cannot find symbol method findRequiredViewAsType(Object,int,String,Class<ImageView>)

### ISSUE THREAD

**Issue by g-ericso** [leighayanid/firebase-auth-android#1]
I am getting this error:
```
Error: cannot find symbol method findRequiredViewAsType(Object,int,String,Class<ImageView>)
```

The following version of butterknife module is inconsistent:
```
apt 'com.jakewharton:butterknife-compiler:8.4.0'
...
compile 'com.jakewharton:butterknife:8.1.0'
```

**Comment by g-ericso** [comment]
Reference the fix in stackoverflow:
https://stackoverflow.com/questions/38212307/butterknife-error-cannot-find-symbol-method-findrequiredviewastype

**Comment by leighayanid** [comment]
Hi. This repo is actually outdated and I haven't touch the code for a while now. I see the issue is about incompatibilities with the butterknife dependency version and the apt version. Feel free to change the code and create a pull request. Thank you.

**Comment by leighayanid** [comment]
Hi. This repo is actually outdated and I haven't touch the code for a while now. I see the issue is about incompatibilities with the butterknife dependency version and the apt version. Feel free to change the code, create and submit a pull request. Thank you.
